require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '11.0'

target 'app65' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => false
  )

  target 'app65Tests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable the next line.
  
  # Fix Flipper versions to ensure compatibility and stability
  use_flipper!({
    'Flipper' => '0.252.0',
    'Flipper-Glog' => '0.5.0.5'
  })

  post_install do |installer|
    installer.pods_project.targets.each do |target|
      # Fix RCT-Folly build settings for C++14 compatibility
      if target.name == 'RCT-Folly'
        target.build_configurations.each do |config|
          config.build_settings['CLANG_CXX_LANGUAGE_STANDARD'] = 'c++14'
        end
      end
    end
    react_native_post_install(installer)
  end
end
